export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
    return (
        <html lang="en">
            <body cz-shortcut-listen="true">{children}</body>
        </html>
    );
};

export default RootLayout;
